"""Three-layer prompt assembly for state machine workflows.

Assembles prompts from:
1. Global prompt — loaded from a .md file referenced in config
2. Stage prompt — loaded from the state's prompt .md file
3. Lifecycle injection — auto-generated from config + Linear data
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import BaseLoader, Environment, Undefined

from .config import LinearStatesConfig, ServiceConfig, StateConfig
from .models import Issue
from .tracking import get_comments_since, get_last_tracking_timestamp

log = logging.getLogger(__name__)


def load_prompt_file(path: str, workflow_dir: str | Path) -> str:
    """Load a .md prompt file relative to the workflow directory."""
    p = Path(path)
    if not p.is_absolute():
        p = Path(workflow_dir) / p
    p = p.resolve()
    if not p.exists():
        raise FileNotFoundError(f"Prompt file not found: {p}")
    return p.read_text()


def render_template(template_str: str, context: dict[str, Any]) -> str:
    """Render a Jinja2 template string with the given context."""
    env = Environment(loader=BaseLoader(), undefined=_SilentUndefined)
    template = env.from_string(template_str)
    return template.render(**context)


class _SilentUndefined(Undefined):
    """Jinja2 undefined that renders as empty string instead of raising."""

    def __str__(self) -> str:
        return ""

    def __iter__(self) -> Any:
        return iter([])

    def __bool__(self) -> bool:
        return False

    def _fail_with_undefined_error(self, *args: Any, **kwargs: Any) -> Any:
        return _SilentUndefined()

    def __getattr__(self, name: str) -> _SilentUndefined:
        if name.startswith("_"):
            raise AttributeError(name)
        return _SilentUndefined()

    def __getitem__(self, name: str) -> _SilentUndefined:
        return _SilentUndefined()


def build_template_context(
    issue: Issue,
    state_name: str,
    run: int = 1,
    attempt: int = 1,
    last_run_at: str | None = None,
) -> dict[str, Any]:
    """Build the Jinja2 template context dict from issue and run metadata."""
    return {
        "issue_id": issue.id,
        "issue_identifier": issue.identifier,
        "issue_title": issue.title,
        "issue_description": issue.description or "",
        "issue_url": issue.url or "",
        "issue_priority": issue.priority,
        "issue_state": issue.state,
        "issue_branch": issue.branch_name or "",
        "issue_labels": issue.labels,
        "state_name": state_name,
        "run": run,
        "attempt": attempt,
        "last_run_at": last_run_at or "",
    }


def build_lifecycle_section(
    issue: Issue,
    state_name: str,
    state_cfg: StateConfig,
    linear_states: LinearStatesConfig,
    run: int = 1,
    is_rework: bool = False,
    recent_comments: list[dict[str, Any]] | None = None,
) -> str:
    """Generate the auto-injected lifecycle section."""
    lines: list[str] = []

    lines.append("---")
    lines.append("<!-- AUTO-GENERATED BY STOKOWSKI — DO NOT EDIT -->")
    lines.append("")
    lines.append("## Lifecycle Context")
    lines.append("")
    lines.append(f"- **Issue:** {issue.identifier} — {issue.title}")
    if issue.url:
        lines.append(f"- **URL:** {issue.url}")
    lines.append(f"- **State:** {state_name}")
    lines.append(f"- **Run:** {run}")
    lines.append("")

    if is_rework:
        lines.append("### Rework")
        lines.append("")
        lines.append(
            "This is a **rework run**. A previous submission was reviewed "
            "and sent back for changes."
        )
        lines.append("")
        if recent_comments:
            lines.append("**Review comments:**")
            lines.append("")
            for comment in recent_comments:
                body = comment.get("body", "").strip()
                created = comment.get("createdAt", "")
                if body:
                    lines.append(f"> {body}")
                    if created:
                        lines.append(f"> — {created}")
                    lines.append("")
        lines.append(
            "Address the feedback above before resubmitting."
        )
        lines.append("")

    if not is_rework and recent_comments:
        lines.append("### Recent Activity")
        lines.append("")
        for comment in recent_comments:
            body = comment.get("body", "").strip()
            created = comment.get("createdAt", "")
            if body:
                lines.append(f"> {body}")
                if created:
                    lines.append(f"> — {created}")
                lines.append("")

    if state_cfg.transitions:
        lines.append("### Transitions")
        lines.append("")
        for trigger, target in state_cfg.transitions.items():
            lines.append(f"- `{trigger}` → **{target}**")
        lines.append("")

    lines.append("### When Done")
    lines.append("")
    lines.append(
        "When you have completed your work, post a summary comment on "
        "the Linear issue describing what was done and any decisions made."
    )
    lines.append("")
    lines.append("<!-- END STOKOWSKI LIFECYCLE -->")

    return "\n".join(lines)


def assemble_prompt(
    cfg: ServiceConfig,
    workflow_dir: str | Path,
    issue: Issue,
    state_name: str,
    state_cfg: StateConfig,
    run: int = 1,
    is_rework: bool = False,
    attempt: int = 1,
    last_run_at: str | None = None,
    comments: list[dict[str, Any]] | None = None,
) -> str:
    """Orchestrate three-layer prompt assembly."""
    context = build_template_context(
        issue=issue,
        state_name=state_name,
        run=run,
        attempt=attempt,
        last_run_at=last_run_at,
    )

    parts: list[str] = []

    if cfg.prompts.global_prompt:
        try:
            raw = load_prompt_file(cfg.prompts.global_prompt, workflow_dir)
            rendered = render_template(raw, context)
            parts.append(rendered)
        except FileNotFoundError:
            log.warning(
                "Global prompt file not found: %s", cfg.prompts.global_prompt
            )

    if state_cfg.prompt:
        try:
            raw = load_prompt_file(state_cfg.prompt, workflow_dir)
            rendered = render_template(raw, context)
            parts.append(rendered)
        except FileNotFoundError:
            log.warning(
                "Stage prompt file not found for state '%s': %s",
                state_name,
                state_cfg.prompt,
            )

    recent: list[dict[str, Any]] = []
    if comments:
        last_ts = get_last_tracking_timestamp(comments)
        recent = get_comments_since(comments, last_ts)

    lifecycle = build_lifecycle_section(
        issue=issue,
        state_name=state_name,
        state_cfg=state_cfg,
        linear_states=cfg.linear_states,
        run=run,
        is_rework=is_rework,
        recent_comments=recent,
    )
    parts.append(lifecycle)

    return "\n\n".join(parts)
